import {createWorld} from './world.js';
const {chapters,escape}=window.CONVERSATION;
const $=s=>document.querySelector(s);let index=0,world,explore=false,still=matchMedia('(prefers-reduced-motion: reduce)').matches;
const dialog=$('#drawer');
$('#route').innerHTML=window.CONVERSATION.groups.map((g,i)=>`<button data-group="${i}" aria-current="false"><b>${i+1}</b><span>${g}</span></button>`).join('');
$('#route').querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>{stopTour();go(chapters.findIndex(c=>c.group===Number(b.dataset.group)));});
let tour=null;
function stopTour(){clearInterval(tour);tour=null;$('#tour').setAttribute('aria-pressed','false');$('#tour').textContent='▷ סיור';}
$('#tour').onclick=()=>{if(tour){stopTour();return;}$('#tour').setAttribute('aria-pressed','true');$('#tour').textContent='Ⅱ עצירה';if(index===chapters.length-1)go(0);tour=setInterval(()=>{if(dialog.open||document.hidden)return;if(index===chapters.length-1){stopTour();return;}go(index+1);},12000);};
function open(html){dialog.classList.remove('data-dialog');$('#drawer-content').innerHTML='<p class="dialog-credit">תוכנית המחקר בהובלת פרופ׳ דורית הדר־שובל · אלעד רפואה</p>'+html;dialog.showModal();}
const zoom=document.createElement('button');zoom.id='datazoom';zoom.textContent='הגדלת נתונים';zoom.title='הגדלת נתוני התחנה (G)';$('#sources').before(zoom);
zoom.onclick=()=>{const c=chapters[index];stopTour();open('<h2>'+c.title+'</h2>'+c.labels.filter(l=>l.html.includes('class="exhibit"')).map(l=>l.html).join('')+'<p class="zoom-caption">'+c.caption+'</p>');dialog.classList.add('data-dialog');};
dialog.querySelector('.close').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});
function draw(){const c=chapters[index];$('#mobile-notes').innerHTML=c.labels.map(l=>'<div class="world-label '+(l.tone||'')+'">'+l.html+'</div>').join('')+`<p class="mobile-qualification">${c.caption||''}</p>`;$('#mobile-notes').scrollTop=0;$('#chapter-title').textContent=c.title;$('#chapter-purpose').textContent=c.purpose||'';$('#chapter-section').textContent=c.section;$('#chapter-heading').classList.toggle('opening',false);$('#chapter-short').textContent=c.short;$('#counter').textContent=`שקף ${c.slide} מתוך ${chapters.length}`;$('#caption').textContent=c.caption||'';$('#progress span').style.width=(index+1)/chapters.length*100+'%';$('#previous').disabled=index===0;$('#next').disabled=index===chapters.length-1;$('#route').querySelectorAll('[data-group]').forEach(b=>b.setAttribute('aria-current',String(Number(b.dataset.group)===c.group)));document.title=c.title+' — בתוך השיחה';}
function go(i,instant=false){index=Math.max(0,Math.min(chapters.length-1,i));explore=false;$('#explore').setAttribute('aria-pressed','false');$('#explore-hint').hidden=true;draw();zoom.hidden=!chapters[index].labels.some(l=>l.html.includes('class="exhibit"'));world?.setChapter(index,instant);history.replaceState(null,'','#'+(index+1));}
$('#next').onclick=()=>{stopTour();go(index+1);};$('#previous').onclick=()=>{stopTour();go(index-1);};
$('#overview').onclick=()=>{open('<h2>המסע לפי המצגת המקורית</h2><div class="map-grid">'+chapters.map((c,i)=>`<button class="map-stop" data-go="${i}" aria-current="${i===index}"><small>שקף ${c.slide} · ${c.section}</small><span>${c.short}</span></button>`).join('')+'</div>');dialog.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{stopTour();dialog.close();go(Number(b.dataset.go));});};
$('#sources').onclick=()=>{const c=chapters[index],ids=[...new Set(c.labels.flatMap(l=>[...l.html.matchAll(/data-fact="([^"]+)"/g)].map(m=>m[1])))];open(`<h2>${c.short}</h2><p>${c.notes||''}</p>${c.refs?'<h3>לקריאה</h3>'+c.refs.map(([label,url])=>`<p><a href="${url}" target="_blank" rel="noopener">${label}</a></p>`).join(''):''}<h3>נתונים ומקורות</h3><p>מתוך המצגת המקורית ורשומת העובדות של הפרויקט. כל נתון מוצג עם המקור והקטע התומך בו.</p>${ids.map(id=>{const f=window.SOURCE_FACTS.facts[id];return `<details class="source-item"><summary>${escape(f.display)} · <bdi>${id}</bdi></summary><p>${escape(f.source)}</p><pre>${escape(typeof f.quote==='string'?f.quote:JSON.stringify(f.quote))}</pre></details>`;}).join('')}<h3>הערות מהמצגת המקורית</h3>${(c.slides||[]).map(num=>{const s=window.SOURCE_DECK.find(s=>s.number===num);return s?`<details class="source-item"><summary>שקף ${num}</summary><p>${s.notes.map(escape).join('<br>')}</p></details>`:''}).join('')}`);};
$('#reading').onclick=()=>open('<h2>בתוך השיחה — גרסה לקריאה</h2>'+chapters.map(c=>`<section class="reading-chapter"><h3>${c.title}</h3>${c.labels.map(l=>`<div class="world-label">${l.html}</div>`).join('')}<p>${c.caption||''}</p><p>${c.notes||''}</p></section>`).join(''));
$('#explore').onclick=()=>{explore=!explore;world?.setExplore(explore);$('#explore').setAttribute('aria-pressed',String(explore));$('#explore-hint').hidden=!explore;if(!explore)go(index);};
$('#motion').onclick=()=>{still=!still;world?.setMotion(still);$('#motion').setAttribute('aria-pressed',String(still));$('#motion').title=still?'התנועה מופחתת':'תנועה מלאה';if(still)go(index,true);};
$('#fullscreen').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen().catch(()=>{});};
addEventListener('keydown',e=>{if(dialog.open)return;if(['ArrowLeft','ArrowDown','PageDown',' '].includes(e.key)){e.preventDefault();stopTour();go(index+1);}if(['ArrowRight','ArrowUp','PageUp'].includes(e.key)){e.preventDefault();stopTour();go(index-1);}if(e.key==='Home'){stopTour();go(0);}if(e.key==='End'){stopTour();go(chapters.length-1);}if(e.key.toLowerCase()==='m')$('#overview').click();if(e.key.toLowerCase()==='n')$('#sources').click();if(e.key.toLowerCase()==='f')$('#fullscreen').click();});
addEventListener('hashchange',()=>go((parseInt(location.hash.slice(1))||1)-1));
addEventListener('keydown',e=>{if(!dialog.open&&e.key.toLowerCase()==='g'&&!zoom.hidden)zoom.click();});
const requested=(parseInt(location.hash.slice(1))||1)-1;go(requested,true);
try{await document.fonts.load('500 30px Assistant');world=await createWorld($('#world'),chapters);go(requested,true);$('#loading').classList.add('done');$('#loading').setAttribute('aria-hidden','true');window.CONVERSATION_READY=true;window.getConversationState=()=>world.getState();}catch(error){console.error(error);$('#loading-status').textContent='המרחב לא נטען. אפשר לפתוח את גרסת הקריאה מהכפתור למטה.';$('#loading').style.pointerEvents='none';$('#loading').style.zIndex='3';$('#reading').style.display='block';}
